//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GHelperLogic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GHelperLogic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DummyGHUBSettings {
            get {
                object obj = ResourceManager.GetObject("DummyGHUBSettings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DummyGHUBSettings_backup {
            get {
                object obj = ResourceManager.GetObject("DummyGHUBSettings_backup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties\DummyGHUBSettings.json.
        /// </summary>
        public static string DummyGHUBSettingsRelativePath {
            get {
                return ResourceManager.GetString("DummyGHUBSettingsRelativePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to runas.
        /// </summary>
        public static string ElevatedPermissionsVerb {
            get {
                return ResourceManager.GetString("ElevatedPermissionsVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .png.
        /// </summary>
        public static string FileExtensionPNG {
            get {
                return ResourceManager.GetString("FileExtensionPNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilePermissionsUtility.exe.
        /// </summary>
        public static string FilePermissionsUtilityExecutableName {
            get {
                return ResourceManager.GetString("FilePermissionsUtilityExecutableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GHelper.
        /// </summary>
        public static string GHelperAppDataDirectoryName {
            get {
                return ResourceManager.GetString("GHelperAppDataDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.log.
        /// </summary>
        public static string GHelperLogFileName {
            get {
                return ResourceManager.GetString("GHelperLogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.json.
        /// </summary>
        public static string GHubConfigFileName {
            get {
                return ResourceManager.GetString("GHubConfigFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LGHUB.
        /// </summary>
        public static string GHubDataDirectoryName {
            get {
                return ResourceManager.GetString("GHubDataDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_cache.
        /// </summary>
        public static string GHubIconCacheDirectoryName {
            get {
                return ResourceManager.GetString("GHubIconCacheDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to depots.
        /// </summary>
        public static string GHubProgramDataDepotsSubdirectoryName {
            get {
                return ResourceManager.GetString("GHubProgramDataDepotsSubdirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to core\applications.
        /// </summary>
        public static string GHubProgramDataImagesStorageRelativePath {
            get {
                return ResourceManager.GetString("GHubProgramDataImagesStorageRelativePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://127.0.0.1:9180/core/applications/.
        /// </summary>
        public static string PosterURLStandardPrefix {
            get {
                return ResourceManager.GetString("PosterURLStandardPrefix", resourceCulture);
            }
        }
    }
}
